### ISSUE TITLE
Fix the merge conflict referenced.

### ISSUE THREAD

**Issue by bryzaguy** [grimxreaper/portpage#1]
Looks like you have a merge conflict that wasn't resolved. Let me know if you need more guidance on fixing it.
https://github.com/grimxreaper/portpage/blob/2b7b357039886f231b89a616caaa37ba857bcf56/index.html#L8

**Comment by grimxreaper** [comment]
I accepted incoming changes and fixed the merge conflict in vs code and pushed changes to the remote repo, I think it is fixed now. Could you let me know if I did that properly? When I look at the code it doesn't show a conflict anymore, but when I click on the reference in your comment above, it does show it, but I don't know if that's just the history or the current version.

**Comment by bryzaguy** [comment]
Looks like it worked! This issue is resolved.
